name: Build RootBridge
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Theos
        uses: Randomblock1/theos-action@v1
      - name: Build Package (rootless)
        run: ./build.sh rootless
      - name: Upload Deb
        uses: actions/upload-artifact@v4
        with:
          name: RootBridge-rootless
          path: build/*rootless.deb
